sudo: required
language: csharp
mono: none
dotnet: 2.1.300
if: tag IS blank
services:
  - docker
before_install:
  - git fetch --unshallow || true
  - dotnet tool install -g dotnet-script
  - export PATH=$PATH:$HOME/.dotnet/tools
script:
  - ./build.sh ci